### ISSUE TITLE
No text shows up when running in dark mode while using iOS 14.6 Beta (18F5065a).

### ISSUE THREAD

**Issue by mandaris** [microdotblog/wavelength#1]
The cursor moves as I type in words but nothing shows up and I can't send to my blog.
Light mode works fine.

![The cursor moves with the words being typed.](https://user-images.githubusercontent.com/86337/117737258-59907f80-b1ae-11eb-842d-ba6eefb77ca3.PNG)

Attached a movie of the usage.
https://user-images.githubusercontent.com/86337/117737221-3f56a180-b1ae-11eb-91bd-d8ec3be7245b.mp4

**Comment by manton** [comment]
Fixed now with today's 1.1.1 release. Thanks @mandaris!
